name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
    branches: [main]

jobs:
  bof-build:
    name: Build and publish tagged release
    if: startsWith( github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: OS Packages
        run: |
          sudo apt-get update --fix-missing && sudo apt-get -y install \
          git build-essential zlib1g zlib1g-dev wget zip unzip \
          mingw-w64 binutils-mingw-w64 g++-mingw-w64 gcc-multilib jq

      - name: Minisign
        run: |
          MINISIGN_TMP=`mktemp -d`
          cd $MINISIGN_TMP
          wget https://github.com/aead/minisign/releases/download/v0.2.0/minisign-linux-amd64.tar.gz
          tar xvf minisign-linux-amd64.tar.gz
          mv ./minisign ~/minisign

      - name: Check out code
        uses: actions/checkout@v2

      - name: Git Fetch Tags
        run: git fetch --prune --unshallow --tags -f

      - name: Build & package artifacts
        run: |
          touch ~/minisign.key && chmod 600 ~/minisign.key
          echo -e "${{ secrets.MINISIGN_PRIVATE_KEY }}" > ~/minisign.key
          
          mkdir packages
          mkdir killdefender_src/artifacts
          mkdir backstab_src/artifacts
          
          cd killdefender_src/src
          x86_64-w64-mingw32-g++ -o ../artifacts/KillDefender.x64.o -Os -c killdefender_bof.cpp -DBOF -D_UNICODE
          cd ..
          VERSION=$(git describe --tags --abbrev=0)
          cat extension.json | jq ".version |= \"$VERSION\"" > ./artifacts/extension.json
          cd artifacts
          tar -czvf ../../packages/kdstab-kill-defender.tar.gz .
          MANIFEST=$(cat extension.json | base64 -w 0)
          cd ../../packages/
          bash -c "echo \"\" | ~/minisign -s ~/minisign.key -S -m ./kdstab-kill-defender.tar.gz -t \"$MANIFEST\" -x kdstab-kill-defender.minisig"
          cd .. 

          cd ./backstab_src
          x86_64-w64-mingw32-gcc -o ./artifacts/backstab.x64.o -Os -c main.c -DBOF -D_UNICODE
          VERSION=$(git describe --tags --abbrev=0)
          cat extension.json | jq ".version |= \"$VERSION\"" > ./artifacts/extension.json
          cd artifacts
          tar -czvf ../../packages/kdstab-backstab.tar.gz .
          MANIFEST=$(cat extension.json | base64 -w 0)
          cd ../../packages/
          echo
          pwd
          ls -l
          echo
          bash -c "echo \"\" | ~/minisign -s ~/minisign.key -S -m ./kdstab-backstab.tar.gz -t \"$MANIFEST\" -x kdstab-backstab.minisig"

      - name: "Publish Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./packages/*.tar.gz
            ./packages/*.minisig
